flink:
  deployment:
    option:
      target: yarn-per-job              # --target <arg> (local|remote|yarn-per-job|yarn-session|run-application)
      detached:                         # -d   (If present, runs the job in detached mode)
      shutdownOnAttachedExit:           # -sae (If the job is submitted in attached mode, perform a best-effort cluster shutdown when the CLI is terminated abruptly, e.g., in response to a user interrupt, such as typing Ctrl + C.)
      zookeeperNamespace:               # -z Namespace to create the Zookeeper sub-paths  for high availability mode
      jobmanager:                       #  -m Address of the JobManager to which to connect. Use this flag to connect to a different JobManager than the one specified in the configuration. Attention: This option is respected only if the  high-availability configuration is NONE
    property: # see: https://ci.apache.org/projects/flink/flink-docs-release-1.12/deployment/config.html
      $internal.application.main: com.hopson.TestDorisSink # main class
      yarn.application.name: TestDorisSink
      yarn.application.node-label: StreamX
      taskmanager.numberOfTaskSlots: 1
      parallelism.default: 2
      jobmanager.memory:
        flink.size:
        heap.size:
        jvm-metaspace.size:
        jvm-overhead.max:
        off-heap.size:
        process.size:
      taskmanager.memory:
        flink.size:
        framework.heap.size:
        framework.off-heap.size:
        managed.size:
        process.size:
        task.heap.size:
        task.off-heap.size:
        jvm-metaspace.size:
        jvm-overhead.max:
        jvm-overhead.min:
        managed.fraction: 0.4
  checkpoints:
    enable: true
    interval: 3000
    mode: EXACTLY_ONCE
    timeout: 300000
    unaligned: true
  watermark:
    interval: 10000
    # 状态后端
  state:
    backend: # see https://ci.apache.org/projects/flink/flink-docs-release-1.12/ops/state/state_backends.html
      value: filesystem # 保存类型('jobmanager', 'filesystem', 'rocksdb')
      memory: 5242880 # 针对jobmanager有效,最大内存
      async: false    # 针对(jobmanager,filesystem)有效,是否开启异步
      incremental: true #针对rocksdb有效,是否开启增量
      #rocksdb 的配置参考 https://ci.apache.org/projects/flink/flink-docs-release-1.12/deployment/config.html#rocksdb-state-backend
      #rocksdb配置key的前缀去掉:state.backend
      #rocksdb.block.blocksize:
    checkpoints.dir: file:///tmp/chkdir
    savepoints.dir: file:///tmp/chkdir
    # 重启策略
  restart-strategy:
    value: fixed-delay  #重启策略[(fixed-delay|failure-rate|none)共3个可配置的策略]
    fixed-delay:
      attempts: 3
      delay: 5000
    failure-rate:
      max-failures-per-interval:
      failure-rate-interval:
      delay:

jdbc:
  doris:
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://10.2.39.142:9030/example_db
    username: hst
    password: 123456
    #semantic: AT_LEAST_ONCE
    batch.size: 500
    interval: 30000
  bigdataTableProcess:
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://10.2.39.40:3306/hopsonone_market_analysis?useSSL=false&allowPublicKeyRetrieval=true
    username: canal_bigdata
    password: canal@Hopson2020
    connectionTimeout: 30000
    idleTimeout: 30000
    maxLifetime: 30000
    minimumIdle: 1
    maximumPoolSize: 5
# hbase
hbase:
  zookeeper.quorum: dev-hadoop-1,dev-hadoop-2,dev-hadoop-6
  zookeeper.property.clientPort: 2181
  zookeeper.session.timeout: 1200000
  rpc.timeout: 5000
  client.pause: 20

# source config....
kafka.source:
  bootstrap.servers: dev-hadoop-7:9092,dev-hadoop-8:9092,dev-hadoop-10:9092
  #topic: hst_ods_mall_order_goods_order_detail
  topic: test__business,test_market,test_wx_auth_log
  group.id: dsa1d
  auto.offset.reset: earliest
    #enable.auto.commit: true
    #start.from:
    #timestamp: 1591286400000 #指定timestamp,针对所有的topic生效
    #offset: # 给每个topic的partition指定offset
    #topic: kafka01,kafka02
    #kafka01: 0:182,1:183,2:182 #分区0从182开始消费,分区1从183...
  #kafka02: 0:182,1:183,2:182
  #hopsonone_park_gz_tjd_specilog: 0:192,1:196,2:196

kafka.sink:
  bootstrap.servers: dev-hadoop-7:9092,dev-hadoop-8:9092,dev-hadoop-10:9092
  topic: kfk_sink
  transaction.timeout.ms: 1000
  semantic: AT_LEAST_ONCE # EXACTLY_ONCE|AT_LEAST_ONCE|NONE
  batch.size: 1
config.warn:
  qywx: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=dadd7bd2-91ce-46ed-af9b-a99d7f5739b4

doris.sink:
  user: hst
  password: 123456
  port: 8030
  host: 10.2.39.142
  database: example_db
  table: doris_test_sink
timerTask:
  tableName: bigdata_table_process
  delay: 5000
  period: 5000
